## Numpy

Numpy es una librería de python enfocada en el cálculo numérico que nos permite realizar operaciones de una manera sencilla y rápida. Su objeto base es un vector de números denominado Array. Es una alternativa a las listas que hemos visto hasta ahora y nos va a permitir realizar una serie de funciones muy potentes. A diferencia de las listas, donde se opera de forma independiente en cada uno de los elementos, en los Arrays las operaciones se van a realizar sobre todo el Array simultáneamente.

### Importación de NumPy

In [1]:
import numpy as np

### Arrays de NumPy vs Listas tradicionales

In [2]:
# Creación de dos listas tradicionales
a = [1,2,3]
b = [4,5,6]

In [3]:
# Suma de dos listas tradicionales
a + b
# Vemos que el resultado es una nueva lista de 6 elementos

[1, 2, 3, 4, 5, 6]

In [5]:
# Creación de arrays de NumPy
a = np.array([1,2,3])
b = np.array([4,5,6,])

In [6]:
# Al realizar la suma, realziara una operación de matrices
a + b

array([5, 7, 9])

### Ejemplo Índice de Masa Corporal (IMC)

Vamos a calcular el índice de masa corporal sobre los valores peso y altura de tres personas.

In [7]:
# Creamos dos listas con el peso y la altura de tres personas
altura = [1.7,1.65,1.82]
peso = [67,55,72]

El cálculo que hay que hacer para obtener el IMC es dividir el peso entre el cuadrado de la altura.

In [ ]:
# peso/altura **2

Si quisiéramos calcular el IMC mediante listas tradicionales podríamos hacerlo fácilmente usando la función zip(), iterar a través de un bucle for e ir añadiendo los resultados mediante comrpensión de listas del siguiente modo:

In [8]:
[p / a**2 for p, a in zip(peso, altura)]

[23.18339100346021, 20.202020202020204, 21.736505252988767]

El cálculo está bien hecho, pero de este modo es más complicado, entre otras
cosas porque el cálculo se va haciendo secuencialmente elemento a elemento
entre las listas, y en este caso no es mucho problema ya que son listas de solo
3 elementos, pero podría ser un problema al trabajar con listas de miles de
elementos. Se realizar el mismo cálculo de una manera mucho más eficiente
usando los Arrays de NumPy, veamos el ejemplo:

In [9]:
# Creación de arrays con numPy
np_altura = np.array([1.7,1.65,1.82])
np_peso = np.array([67,55,72])

In [10]:
# Aplicación fórmula
imc = np_peso / np_altura **2
imc

array([23.183391  , 20.2020202 , 21.73650525])

Otro uso interesante de los Arrays es que podemos evaluar todos los elemnentos del Array con una simple operación, como por ejemplo saber qué valores son mayores que 21:

In [11]:
# Se nos muestra el True o False en función de si se cumple
imc > 21

array([ True, False,  True])

Si quisieramos obtener sólo los elementos del array que cumplen la condición anterior podemos hacerlo de la siguiente manera:

In [12]:
imc[imc>21]

array([23.183391  , 21.73650525])

### Arrays de dos dimensiones

Con NumPy también podremos crear un Array de dos dimensiones. En realidad es una matriz de m filas por n columnas.

In [15]:
# Vamos a crear un array bidimensional

a = np.array([[2,7,8],[4,8,10 ]])
a

array([[ 2,  7,  8],
       [ 4,  8, 10]])

Si quisieramos obtener el valor 10 de nuestro array de dos dimensiones tendríamos que especificar el índice de la fila seguido del índice de la columna.

In [16]:
a[1,2] #la fila 1 con la colúmna 2, teniendo en cuenta que todo empieza por 0

10

Ahora supongamos que queremoss obtener todas las filas pero solo los valores de las columans primera y segunda. Deberemos hacerlo realizando un slicing

In [17]:
a[:,0:2] # En el primer elemento estamos realizando un primer slice para seleccionar todas las filas
         # El segundo slice estamos seleccionando las columnas, teniendo e cuenta que la última no se añade

array([[2, 7],
       [4, 8]])

### Cálculo estadístico con NumPy

En esta sección veremos algunas de las funciones que nos pueden servir para solucionar algunos cálculos estadísticos de una manera mucho más sencilla y rápida.

In [18]:
# Creamos un Array
temperaturas = np.array([12, 13.5, 13, 14, 13.2, 14.8, 15, 15.16, 16, 16.2,
15.7, 17, 17.2, 16.8, 14, 14.2, 14.7, 16, 17.5])

In [19]:
# Podemos calcular la media o promedio usando mean(array)
np.mean(temperaturas)

15.050526315789472

In [20]:
# La mediana usando la funcion median(array)
np.median(temperaturas)

15.0

In [21]:
# También podemos obtener el valor mínimo con la función min(array)
np.min(temperaturas)

12.0

In [22]:
# Tambíen podemos obtener el valor máximo con la función max(array)
np.max(temperaturas)

17.5

In [24]:
# Para calcular la varianza podremos usar la función var(array) de la siguiente manera:
np.var(temperaturas)

2.2893207756232683

In [26]:
# La desviación estándard podremos obtenerla usando la función std(array)
np.std(temperaturas)

1.5130501563475245

In [27]:
# También tenemos la función percentil(array,y) a la que tendremos que pasarle como argumentos el array y también el percentil que queremos obtener
np.percentile(temperaturas,90)

17.04